### ISSUE TITLE
I would like to become a maintainer of emberx-select

### ISSUE THREAD

**Issue by fivetanley** [adopted-ember-addons/program-guidelines#12]
Hi there,

I've worked in emberx-select before (https://github.com/adopted-ember-addons/emberx-select/graphs/contributors) a bit when I worked at frontside, so I am a bit familiar with the problem domain and codebase.

I saw that it has several betas but no formal 4.x release. I can help accomplish that so that octane users can have a compatible emberx-select release.

Thanks!

**Comment by knownasilya** [comment]
Added you to the repo with write access. @MelSumner can we get him on npm?
