### ISSUE TITLE
No user named adopted-ember-addons

### ISSUE THREAD

**Issue by simonexmachina** [adopted-ember-addons/program-guidelines#2]
When I try to add `adopted-ember-addons` to the maintainers of the package on npm I get a not found error from npm:

```
$ npm owner add adopted-ember-addons ember-notify
npm ERR! owner mutate Failed to update package metadata
npm ERR! code E404
npm ERR! 404 No user named adopted-ember-addons : 136-862e9392b1d82976fd0c858d95a97934
npm ERR! 404
npm ERR! 404  '136-862e9392b1d82976fd0c858d95a97934' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by simonexmachina** [comment]
Re. https://github.com/aexmachina/ember-notify/pull/130

**Comment by MelSumner** [comment]
adopted-ember-addons is the org name- does the org need to be on npm itself?

**Comment by simonexmachina** [comment]
I'm not sure what you're asking @MelSumner. The [guidelines](https://github.com/adopted-ember-addons/program-guidelines) say to "Add adopted-ember-addons to the maintainers of the package on npm", so I've tried to do this but I'm getting the above error.

**Comment by MelSumner** [comment]
@aexmachina I see what you mean- I'm fixing it now.

**Comment by MelSumner** [comment]
@aexmachina I updated the instructions and they should be adequate now. Please let us know if you have any further issues.
