### ISSUE TITLE
further formalization

### ISSUE THREAD

**Issue by ghost** [adopted-ember-addons/program-guidelines#5]
#3 sparked discussion around what we should do as a community to steward adopted addons.

I created this issue as a placeholder for us to continue iterating toward the best solution.

@jelhan would you mind taking the lead? I won't have much time to devote to adopted ember addons due to other commitments.

**Comment by jelhan** [comment]
I can do so. But also not having that much time. So would be more kind of a coordination role. And don't expect everything tomorrow. 😉

But I have some ideas how such a process could be started. Let me take the chance to write them down.

I think a proposal on structure and terminology of such a document would be helpful as a starting point. Mainly to structure the discussion. It should reflect the idea to differentiate between requirements (must), recommendations (should) and proposals (may).

Additionally it would be helpful to get an agreement on some generic criteria to decide which rules to include. It's helpful to have something to refer to in discussions about specific rules in my experience. The adoption in the community could be such a criteria.

I can try to write a proposal at the end of next week.

I hope that this will provide a good foundation to work on specific topics. It should especially allow everyone to write proposals for specific topics - maybe similar to a RFC process. Such topics may include:

- release process (versioning strategy, Changelog etc.)
- support commitments for Ember, Ember CLI, node and others
- coding style (Prettier?)
- aimed test coverage
- TypeScript
- ...

**Comment by jelhan** [comment]
> I can try to write a proposal at the end of next week.

I was a little bit to optimistic here. But I still plan to do it. Good to see that others don't feel blocked by it and start adding more recommendations to the guidelines.
